version: '3.8'

services:
  api:
    build: .
    container_name: certamen2_nginx
    ports:
      - "8081:80"  # Puerto 8081 en el host, 80 en el contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Configuración personalizada (opcional)
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge