sonar.projectKey=certamen2_cicd
sonar.projectName=Certamen2 CI/CD - Nginx
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Lenguajes a analizar
sonar.language=web

# Excluir archivos no relevantes
sonar.exclusions=**/nginx.conf,**/Dockerfile,**/docker-compose*.yml,**/*.md

# Incluir archivos HTML, CSS, JS
sonar.inclusions=**/*.html,**/*.css,**/*.js